### ISSUE TITLE
MoveIt IK plugin?

### ISSUE THREAD

**Issue by gavanderhoorn** [Jmeyer1292/opw_kinematics#1]
Just wondering if you've already written a `KinematicsBase` implementation for this, or if you're planning on doing that.

This would seem to make for an excellent alternative for IKFast, which would remove the need for the generated code, and be much easier to maintain and create.

+💯 for finding this.

**Comment by JeroenDM** [comment]
This package is exactly what I was looking for! :)
I would like to give it a try to create the MoveIt IK plugin.

My initial idea is to structure it as a package outside MoveIt! as is done for the [ur_kinematics](https://github.com/ros-industrial/universal_robot/tree/0e269b817d54dd90f383f255d03394b79ae73326/ur_kinematics).
The implementation can probably be based on [descartes_opw_model](https://github.com/Jmeyer1292/descartes_opw_model) and [descartes_moveit](https://github.com/ros-industrial-consortium/descartes/tree/8db7697ed3dcc2616dc305d3241cbd03a03e5002/descartes_moveit/include/descartes_moveit).

The geometric parameters can be extracted from the robot model at initialization. This probalbly has to include some kind of check to see if the robot is compatible.

I'm still terrible at configuring CMakeList stuff, but I slowly get to understand moveit_core. So I'll see how far I can get :) You can follow the progress [here](https://github.com/JeroenDM/opw_kinematics_plugin).

**Comment by gavanderhoorn** [comment]
Seeing as @JeroenDM wrote something, I guess we can close this.
