### ISSUE TITLE
license issues

### ISSUE THREAD

**Issue by simonschmeisser** [Jmeyer1292/opw_kinematics#11]
Hi @Jmeyer1292 

is there a specific reason why you choose GPLv3 instead of something a bit more relaxed? LGPL, BSD like MoveIt! does , MIT, whatever? I'm really not sure if we can use it currently since it might mean we would need to distribute our software under GPLv3 as well.

Thanks!

**Comment by gavanderhoorn** [comment]
Yes, this is rather unfortunate and could potentially mean that it cannot be used for packages like https://github.com/ros-industrial/fanuc/issues/245.

I second the comment by @simonschmeisser: it would be +100 if the licensing could be changed to one of the non-copyleft licenses. Or perhaps LGPL would be enough, but anything with "GPL" in it makes people look for alternatives is my experience.

**Comment by Jmeyer1292** [comment]
When i implemented this from the paper there were some ambiguities. I found a matlab implementation that i thought was gpl, so i went with that. Looking back, I may have been mistaken. I dont mind changing it as long as @JeroenDM is okay too.

**Comment by JeroenDM** [comment]
That's ok for me, thanks for asking.

It's a good reminder for me that I should pay more attention to the license.
Does this also mean that if I write [a ROS package that depends on opw_kinematics](https://github.com/JeroenDM/arf/blob/bd0412982ed8233431885d3f340944859a3cd9e3/arf_moveit_wrapper/CMakeLists.txt#L11) and I don't add a licence to the github repo that I'm violating GPLv3?

(My argument would be no, since I made the source available and the user downloads opw_kinematics themself, but I really do not know enough about licencing...)

**Comment by JeroenDM** [comment]
Appart from my ignorance about licencing, I still encourage @simonschmeisser to make the source code of his application available if possible within your business context :)

**Comment by gavanderhoorn** [comment]
> It's a good reminder for me that I should pay more attention to the license.
> Does this also mean that if I write [a ROS package that depends on opw_kinematics](https://github.com/JeroenDM/arf/blob/bd0412982ed8233431885d3f340944859a3cd9e3/arf_moveit_wrapper/CMakeLists.txt#L11) and I don't add a licence to the github repo that I'm violating GPLv3?

apart from the possible GPL violations: not specifying any license is even worse. Code without an explicit license is almost toxic and cannot be used ever (or at least: in a commercial context).

**Comment by JeroenDM** [comment]
@gavanderhoorn Thanks for the explanation! I will add LGPL-3.0 to my projects as my [colleges](https://github.com/meco-group/omg-tools) [do](https://github.com/casadi/casadi) for now, when the dependencies allow it. If someone actually wants to use the code and does not agree with the license, they can create an issue as was done here.

Any other suggestions welcome, but I guess this is not the best place to discuss general license choice for ROS-packages.

@Jmeyer1292 Just to avoid confusion, I do not suggest to use (or not use) LGPL-3.0 for this package.

**Comment by gavanderhoorn** [comment]
> @gavanderhoorn Thanks for the explanation! I will add LGPL-3.0 to my projects as my [colleges](https://github.com/meco-group/omg-tools) [do](https://github.com/casadi/casadi) for now, when the dependencies allow it. If someone actually wants to use the code and does not agree with the license, they can create an issue as was done here.
> 
> Any other suggestions welcome, but I guess this is not the best place to discuss general license choice for ROS-packages.

Unless you have a specific reason to use a GPL license, using something like Apache 2.0 or BSD might be better.

But in the end it's up to you of course.

**Comment by Jmeyer1292** [comment]
@gavanderhoorn It's done.

**Comment by gavanderhoorn** [comment]
Awesome. Thanks for this @Jmeyer1292.
