### ISSUE TITLE
opw_kinematics::parameters for UR5 Universal Robot

### ISSUE THREAD

**Issue by lakshmip001** [Jmeyer1292/opw_kinematics#13]
Hi, I want to use this with UR5 Universal Robot, but I dont see parameter values for UR5 in the paper. Kindly please guide me.

**Comment by Jmeyer1292** [comment]
@lakshmip001 The UR robot does not have a  spherical wrist so this package will not work. Please see [the UR repo](https://github.com/ros-industrial/universal_robot/tree/kinetic-devel/ur_kinematics) for this functionality.

**Comment by gavanderhoorn** [comment]
Closing as due to the kinematics of UR robots this is impossible.
