### ISSUE TITLE
Tests failing locally

### ISSUE THREAD

**Issue by simonschmeisser** [Jmeyer1292/opw_kinematics#21]
On our local machines some of the test fail (with big offsets) while on the new travis-ci (#19) they all run successfully. I'm a bit lost, any ideas what to look for?

Find the results of `LC_ALL=C make run_tests >> test-output.txt` here

 https://gist.github.com/simonschmeisser/31f0433b061edb3f91034357b07fd372

I did not see any difference between running it with German or classic locale so it's not that bug this time. We are running melodic on bionic (18.04) with default compiler and cmake.

**Comment by simonschmeisser** [comment]
I found the following warning that I do not understand fully ...

```
In file included from /usr/include/eigen3/Eigen/Core:421:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/sis/Mikado/src/opw_kinematics/include/opw_kinematics/opw_kinematics.h:4,
                 from /home/sis/Mikado/src/opw_kinematics/test/fk_ik_tests.cpp:9:
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h: In function 'opw_kinematics::Transform<T> opw_kinematics::forward(const opw_kinematics::Parameters<T>&, const T*) [with T = double]':
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:631:5: warning: '*((void*)&<anonymous> +16)' is used uninitialized in this function [-Wuninitialized]
     m_functor.assignCoeff(m_dst.coeffRef(row,col), m_src.coeff(row,col));
     ^~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h: In function 'opw_kinematics::Transform<T> opw_kinematics::forward(const opw_kinematics::Parameters<T>&, const T*) [with T = float]':
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:631:5: warning: '<anonymous>' is used uninitialized in this function [-Wuninitialized]
     m_functor.assignCoeff(m_dst.coeffRef(row,col), m_src.coeff(row,col));
     ^~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:631:5: warning: '*((void*)&<anonymous> +4)' is used uninitialized in this function [-Wuninitialized]
     m_functor.assignCoeff(m_dst.coeffRef(row,col), m_src.coeff(row,col));
     ^~~~~~~~~
/usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:631:5: warning: '*((void*)&<anonymous> +8)' is used uninitialized in this function [-Wuninitialized]
     m_functor.assignCoeff(m_dst.coeffRef(row,col), m_src.coeff(row,col));
     ^~~~~~~~~

```

**Comment by gavanderhoorn** [comment]
I don't know why it's happening, but using uninitialised data would lead to:

> On our local machines some of the test fail (with big offsets) [..]

**Comment by simonschmeisser** [comment]
the warning can be toggled by commenting out the last multiplication in
https://github.com/Jmeyer1292/opw_kinematics/blob/1451e169b45f6943be102a2da1bb50b797cd33bd/include/opw_kinematics/opw_kinematics_impl.h#L256

(p.c4 doesn't matter)

**Comment by simonschmeisser** [comment]
Ah, its the type deduction that seems to fail, replacing `auto` by `Vector` fixes the issue

**Comment by gavanderhoorn** [comment]
Wow, that's obscure.

**Comment by simonschmeisser** [comment]
`u` is apparently of type `Eigen::CwiseBinaryOp<Eigen::internal::scalar_sum_op<float, float>, const Eigen::Matrix<float, 3, 1>, const Eigen::Product<Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<float, float>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, const Eigen::Matrix<float, 3, 3> >, const Eigen::Matrix<float, 3, 3> >, Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<float>, Eigen::Matrix<float, 3, 3> >, 3, 1, false>, 0> >` when using `auto`

**Comment by gavanderhoorn** [comment]
Oh, that sort of makes sense.

Eigen is rather lazy, and doesn't necessarily completely evaluate expressions when you assign their result to a variable.

Especially not if you're using `auto`, as then the assignment could result in the *expression* object being assigned to your variable, not the result.

There should be a way to force Eigen to evaluate the expression and return the result, but I can't remember it.

**Comment by simonschmeisser** [comment]
Well using `Vector` does force the evaluation. I'll add this to #19 

btw, could you reproduce the issue?

**Comment by gavanderhoorn** [comment]
> btw, could you reproduce the issue?

I haven't tried. I'm knee-deep in other debugging work.
