### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by Levi-Armstrong** [Jmeyer1292/opw_kinematics#22]
@Jmeyer1292 It looks like I do not have permissions to enable Travis CI. Do you mind enabling travis ci for this repository?

**Comment by gavanderhoorn** [comment]
Alternatively we could consider transferring this repository to `ros-industrial` or another suitable location.

But that would be up to @Jmeyer1292.

**Comment by Levi-Armstrong** [comment]
@Jmeyer1292 friendly reminder :)

**Comment by simonschmeisser** [comment]
@Jmeyer1292 ping :)

**Comment by Levi-Armstrong** [comment]
Complete
