### ISSUE TITLE
qs array

### ISSUE THREAD

**Issue by justin123antony** [Jmeyer1292/opw_kinematics#26]
what is the purpose of qs array and how did it get values?

**Comment by JeroenDM** [comment]
I suppose you are referring to the qs variable in the [forward kinematics function](https://github.com/Jmeyer1292/opw_kinematics/blob/e9fdad209000375fd705daf82402ac99cb322ee0/include/opw_kinematics/opw_kinematics_impl.h#L190):

```c++
template <typename T>
Transform<T> forward(const Parameters<T>& p, const T* qs) noexcept
```

`qs` represents an array with the joint values of the robot and is an input variable to this function.
It gets its values by calling the function.
For example in [fk_ik_tests.cpp](https://github.com/Jmeyer1292/opw_kinematics/blob/e9fdad209000375fd705daf82402ac99cb322ee0/test/fk_ik_tests.cpp#L83):

```c++
// create a reachable pose based on a random robot position
getRandomJointValues(q_rand);  // Here q_rand is an ouput
pose = opw_kinematics::forward(params, q_rand);  // Here q_rand is an input
```

**Comment by JeroenDM** [comment]
@justin123antony Feel free to reopen this if it did not answer your question.

(I kind of closed this by accident since I thought I was going through the `moveit_opw_kinematics_plugin` issues :s but it seems fair to close this anyway.)
