### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by simonschmeisser** [Jmeyer1292/opw_kinematics#39]
We are currently trying to get the `moveit_opw_kinematics_plugin` released: https://github.com/JeroenDM/moveit_opw_kinematics_plugin/issues/40

The goal is to replace current ikfast plugins in ROS-I repositories like discussed at length here: https://github.com/ros-industrial/fanuc/issues/245

There is also a open PR in MoveIt setup assistant to easily allow loading parameters for this library/plugin from a yaml file distributed as part of ROS-I : https://github.com/ros-planning/moveit/pull/1997

One of the requirements would be a release of this library, is anybody up to it or can I help in some way?

**Comment by gavanderhoorn** [comment]
To release a package, we'd need a release repository. Those can be created "anywhere" on github.

We'd also need appropriate tags in this repository.

I don't have push access here, but @Levi-Armstrong does.

If releasing is not a priority/desirable here, a fork could be used.

Finally: this package is a pure CMake package, I'm not entirely sure whether there are any gotches wrt Bloom -- other than just doing a [third party release](http://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty).

**Comment by simonschmeisser** [comment]
If @Jmeyer1292 is interested I guess this could also be moved to ROS-I?

**Comment by Levi-Armstrong** [comment]
The latest version has been release and should be available soon.
