### ISSUE TITLE
Further explanation about offset and sign correction parameters

### ISSUE THREAD

**Issue by Hawxxer** [Jmeyer1292/opw_kinematics#59]
Can someone further explain this two variables to me? 
I try to implement the opw kinematics for a robot arm at our university, but cant wrap my head around this two parameters.
Can I extract them from the urdf? 
Thank you in advance!

**Comment by Levi-Armstrong** [comment]
The offset is to account for zero position differences between the physical robot and the derived equations. The images show the zero position of the robot for the equations. If this is not the zero position of your robot then you need to use the offset. For example most industrial manipulators require a 90deg offset for joint 3. 

The sign correction is similar. If the positive direction shown in the drawing is not the positive direction of the joint on the physical robot then you must set it to -1.

**Comment by Hawxxer** [comment]
Thank you very much, this helped me to implement it. 
Maybe if someone stumble about this. [URDF Viz](https://github.com/openrr/urdf-viz) helped me to understand how the axis align, as you can edit the urdf values and easily reload the model on the fly. Also my rotation values were not accurate enough in my URDF. (Like I defined one rpy value as "0 0 3.141" which is not accurate enough, after changing to "0 0 3.14159265359" it worked)
