### ISSUE TITLE
Advice on how to set up new robot

### ISSUE THREAD

**Issue by fishbotics** [Jmeyer1292/opw_kinematics#63]
Hi all,

I'm looking into how to set up the Franka Panda with OPW. I'm new to OPW (I've most used IKFast). 

1. I'm not even sure if this robot is OPW-qualified. It's a 7-DOF robot and when I use IKFast, I fix the tool joint and then solve IK. I assume that would also work for OPW?
2. I have the DH parameters, but not the OPW ones. Does anyone have tips on how to get started? I'll attach an image from their docs:

![image](https://user-images.githubusercontent.com/45679966/166990400-b6bc8c74-7582-4940-800b-139b30c7715c.png)

**Comment by Levi-Armstrong** [comment]
I almost certain you will have to use ikfast for this since it is not a spherical wrist and has 7 DOF.

**Comment by fishbotics** [comment]
Rats :(
