### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by yvanblanchard** [Jmeyer1292/opw_kinematics#68]
Hello,

Could you please share your performances analysis results ? including comparison with IKFast (I saw IKF files in Test folder), for this same ABB IRB 2400 robot test case.

I compiled the test as it (with my Intel Core i7, 2.7 GHz, Win10 x64), and I got 120ms (one single IK, mean value, for hundreds of tests). 
I found this duration pretty slow , expecting analytical closed forms to have micro-sec order.

Thank you.

**Comment by Levi-Armstrong** [comment]
What commands did you use to build the repository?

**Comment by yvanblanchard** [comment]
Thank you.
I think I found the solution. I used a bad way to measure time (std time instead of chrono). Now, I have one micro second for one single IK, which is much better!
Can you confirm you have (pretty much) the same for your test case ?

**Comment by yvanblanchard** [comment]
Do you know specific build commands to optimize runtime performances ?

**Comment by Levi-Armstrong** [comment]
I just wanted to make sure you were building in release. `-DCMAKE_BUILD_TYPE=Release` I do not believe we currently have any benchmarks on this repo, but the 1 us seems good.
