### ISSUE TITLE
Define rotations for robot pose

### ISSUE THREAD

**Issue by yvanblanchard** [Jmeyer1292/opw_kinematics#70]
Hello,

I tried to define rotation angles (RPY) for the robot pose (target), but it does not seem to work.
Could you please tell me if this syntax is correct or not ?

![image](https://user-images.githubusercontent.com/63931618/177564114-9e325647-7665-462a-8259-e3adddb34936.png)

Other question:
Please remind me how robot wrist singularities are managed with the library (if the target pose implies robot J5 axis with null value, does the lib supposed to give articular results ?)

Thank you.

**Comment by Levi-Armstrong** [comment]
What are the results you are getting and what did you expect?

**Comment by yvanblanchard** [comment]
Sorry, I did a last testing and I had a small error in my code for transferring the angle values. It seems to work fine now with the quaternion form.

Could you also please tell me about wrist singularities ?

Thank you again.

**Comment by Levi-Armstrong** [comment]
> Could you also please tell me about wrist singularities ?

It will provide the solution near zero.

**Comment by yvanblanchard** [comment]
Thank you for your help!
