### ISSUE TITLE
IK solve for point-orientation pose (5-axis)

### ISSUE THREAD

**Issue by yvanblanchard** [Jmeyer1292/opw_kinematics#71]
Hello,

Is it possible with the current algorithm to set a 5-axis target/pose (point + orientation vector), instead of 6-axis ?
I know it's possible with openRave IK-Fast, but it would be great to have it with OPW.

Thank you

**Comment by Levi-Armstrong** [comment]
How is this possible with opeRave IK-Fast?

**Comment by gavanderhoorn** [comment]
By generating a solver specifically for 5 dof. Depending on the configuration, it ignores one of the dimensions in the IK request.

**Comment by Levi-Armstrong** [comment]
> By generating a solver specifically for 5 dof. Depending on the configuration, it ignores one of the dimensions in the IK request.
> 
> See [this](https://github.com/ros-planning/moveit2/blob/54b1a98484ebcd4fe9758fbb2e4026a4ebf4cb66/moveit_kinematics/ikfast_kinematics_plugin/templates/ikfast61_moveit_plugin_template.cpp#L79-L144=) for an enumeration of the variants IKFast supports.

More interested in how it does this under the hood. I has to be making some assumption because infinite solution exists depending on how finely you samples around the z-axis.

**Comment by yvanblanchard** [comment]
would it be possible for this request to change a bit the equations in order to not consider the last sixth axis/DOF (or considering constant null value) ?
Thank you

**Comment by Levi-Armstrong** [comment]
I think I may have misunderstood the original post. Is this for a 5DOF robot or 6DOF robot and you would like to just provide point and normal vector?

**Comment by yvanblanchard** [comment]
It is for a six axis robot (spherical wrist), but don’t care about robot pose (transverse tool vector) ; the target has only tcp origin and tool direction

**Comment by yvanblanchard** [comment]
> Then why not not compute the the rotation matrix using the normal `Eigen::AngleAxisd(0, normal)` and provide the full matrix to opw. Then zero out the sixth joint value?

I’m not sure to understand. Do you think there is no need to modify the actual code of opw solver ?

**Comment by Levi-Armstrong** [comment]
I don't think so. If you do not care about the sixth joints rotation. Then you can using the information you have to create an Eigen::Isometry3d pose using the point normal. Then feed this to OPW kinematics solver and get the joint solution then ignore the sixth joints value.
