### ISSUE TITLE
Support robot KuKa iiwa 7 axis ?

### ISSUE THREAD

**Issue by yvanblanchard** [Jmeyer1292/opw_kinematics#74]
I was wondering if the opw kinematics solver is able to support the iiwa7 LBR robot ?
Thank you.

https://www.researchgate.net/profile/Sebastian-Doliwa/publication/344451115_Calculation_of_the_inverse_kinematics_for_the_KUKA_LBR_iiwa_R800_7_DOF/links/6380cffdc2cb154d29270973/Calculation-of-the-inverse-kinematics-for-the-KUKA-LBR-iiwa-R800-7-DOF.pdf?origin=publication_detail

**Comment by Levi-Armstrong** [comment]
I would say no, but the paper looks straight forward to create a separate package which implements the paper because this should be applied to other 7 dof manipulators with identical joint configurations.

**Comment by yvanblanchard** [comment]
ok thank you Levi
