### ISSUE TITLE
Here are robot parameters for KUKA KR240 R3330

### ISSUE THREAD

**Issue by yvanblanchard** [Jmeyer1292/opw_kinematics#77]
KUKA KR240 R3330:
![image](https://github.com/Jmeyer1292/opw_kinematics/assets/63931618/e2527535-142c-43fc-a890-e80ad9ba8f1e)

**Parameters:**

  a1 = 0.500
  a2 = 0.055
  b = 0.00
  c1 = 1.045
  c2 = 1.300
  c3 = 1.525
  c4 = 0.290

Offset correction (opw convention):
  offsets[2] = -M_PI / 2.0
  
Sign correction:
J1=J4 =J6 = -1

Need to apply offset values for axes J2 and J3 (for KUKA controller convention):
J2 = -90deg
J3 = +90deg

**Test:**

![image](https://github.com/Jmeyer1292/opw_kinematics/assets/63931618/e8e82033-e6d1-46e6-b6df-e72f8bd154f3)

**Comment by Levi-Armstrong** [comment]
Thank you. @marip8 How do you think we should manage this? Should we just have a single header which we put these in to build up a database and use the ROS Industrial URDF naming convention for the definition?

**Comment by marip8** [comment]
- I think I would rather store these parameters as a YAML file instead of a c++ header and provide a parser from YAML to OPW c++ struct
- I think I would rather not store parameters for a bunch of robots in this repo
  - Some repos (like [`motoman`](https://github.com/ros-industrial/motoman/blob/433be15f6a27cb9a5715cc3887b1cd15ff33a8cb/motoman_gp4_support/config/opw_parameters_gp4.yaml) and [`abb`](https://github.com/ros-industrial/abb_experimental/blob/20b9cf86ad274e4f98540b9c9efe59f94245d2d1/abb_irb1200_7_70_moveit_config/config/kinematics.yaml) ) have been storing these parameters as YAML files in the support package. I think it makes more sense to store the information there closer to the other information you need for doing planning (e.g., URDF, meshes, Tesseract/MoveIt configuration information, etc.)
  - For robots without support packages, we could open a discussion on the repo to provide these parameters for reference until the support package gets created

**Comment by yvanblanchard** [comment]
sorry @marip8 , I did not know the best way to share those parameters. 
But I think it can clearly save time to people to get them.
I think a good way would consist to store them in URDF file, using a dedicated XML tag (even if the existing URDF format/convention does not manage them), and find the best repo (ROS?) for managing/sharing the urdf files of all (or most of) the robots.

**Comment by yvanblanchard** [comment]
@Levi-Armstrong @marip8 
I found somethign wrong with calculations for this robot: 
you can notice that the last (J6) axis has not the expected value: here 7.59 degrees, but my target frame has orientation vector which are aligned with base coordinate system, i.e. X = (-1 ; 0 ; 0) , Y= (0 ; 0; 0) , Z= (0; 0; -1.0) ; so the expected J6 value should be 0.

**Comment by gavanderhoorn** [comment]
> I think a good way would consist to store them in URDF file, using a dedicated XML tag (even if the existing URDF format/convention does not manage them), [..]

seeing as OPW (and its various implementations) see usage outside of ROS, perhaps using URDF to store these handful of constants is not necessarily a good idea.

The "ROS world" can easily load a `.yaml`, and that would make these values available to everyone, whether they use ROS or not.

**Comment by yvanblanchard** [comment]
> > I think a good way would consist to store them in URDF file, using a dedicated XML tag (even if the existing URDF format/convention does not manage them), [..]
> 
> seeing as OPW (and its various implementations) see usage outside of ROS, perhaps using URDF to store these handful of constants is not necessarily a good idea.
> 
> The "ROS world" can easily load a `.yaml`, and that would make these values available to everyone, whether they use ROS or not.

Ok, but please notice that URDF format is not only used by ROS users, but also now in plenty of software (NVidia omniverse, Matlab, Unity, Blender,..)

**Comment by gavanderhoorn** [comment]
But we typically use XACRO in ROS, not URDF.

And parsing a `.xacro` without first running it through `xacro` to convert to URDF is often non-trivial, making it non-trivial for non-ROS users to access the data.

I would suggest to store data in formats that are as easy as possible to read/load, and in my opinion, YAML wins over URDF.

**Comment by Levi-Armstrong** [comment]
I also prefer yaml and given the light weight nature of these parameters I do not feel they need to kept in a separate repository. I think have a single yaml file in the repository which should be fine.

**Comment by Levi-Armstrong** [comment]
@yvanblanchard I went ahead and created a [wiki page](https://github.com/Jmeyer1292/opw_kinematics/wiki/Robot-Data) where this data can be stored. Can you review and confirm it is correct?

**Comment by yvanblanchard** [comment]
> @yvanblanchard I went ahead and created a [wiki page](https://github.com/Jmeyer1292/opw_kinematics/wiki/Robot-Data) where this data can be stored. Can you review and confirm it is correct?

@Levi-Armstrong  The offset to apply is only for J2 axis (opw kinematics / paper convention). 
But the 'reference' robot position usually uses both J2 and J3 axes non-null values (-90deg and +90deg respectively, see picture of DELMIA V5 software). The KUKA controller (or Siemens NC) uses those offsets in practice.
But for opw kin solver, only J2 axis needs an offset (-90deg).
Sorry for the confusion.

![image](https://github.com/Jmeyer1292/opw_kinematics/assets/63931618/7fbd5d8d-0fad-41cb-93ef-792b05319025)
